[package]
name = "cribbage"
version = "0.1.0"
authors = ["rsmith20"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
strum = "0.17.1"
strum_macros = "0.17.1"
